# =======================
# Stage 1 - Build
# =======================
FROM maven:3.9.6-eclipse-temurin-21 AS build

# # Create app directory
WORKDIR /app

# copiar pom.xl
COPY pom.xml . 

# # descargar dependencias
RUN mvn dependency:go-offline -B

# copiar codigo aplicacion
COPY src ./src

RUN mvn clean package -DskipTests

# =======================
# Stage 2 - Desplegaar
# =======================
FROM eclipse-temurin:21-jdk-jammy AS deploy

WORKDIR /app

# Copy only the JAR from the build stage
COPY --from=build /app/target/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
 