

services:
  db:  

    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: johan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog_platform 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/
    command: ["-c", "log_statement=all"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "johan"]
      interval: 5s
      timeout: 5s
      

  gestion-biblioteca:
    build:
      context: ./gestion-biblioteca
      dockerfile: Dockerfile
    container_name: gestion_biblioteca
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/blog_platform
      SPRING_DATASOURCE_USERNAME: johan
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
